language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-node-travis-env --build-arg FAVORITE_FOOD=${FAVORITE_FOOD} .
  - docker tag simple-node-travis-env fotso0244/simple-node-travis:with-env-latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fotso0244/simple-node-travis:with-env-latest
